// models will look something like this (with rules && validations occuring in firebase)
var user = {
  "firstName": "Brad",
  "lastName": "Vautour",
  "dob":{
    "month": 1,
    "day": 15,
    "year": 1992
  },
  "username": "bvautour",
  "password": "pizzaisawesome",
  "customer":{
    "id": ""//generated by stripe when card is stored and everything else is handled by stripe
  }

}

module.exports = user;
